### ISSUE TITLE
X!Tandem version 

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/THIRDPARTY#10]
from a build with recent checkouts of the respective development branches:
```
--   + X! Tandem binary found at tandem.exe -> Enabling corresponding tests.
--   - X! Tandem too old (). Please provide an X! Tandem version >= 2013.09.01 to enable the tests.
```

**Comment by jpfeuffer** [comment]
Works for the current Mac version. Can you post the XTandem output of your version?

**Comment by jpfeuffer** [comment]
Btw: This repo has no develop branch.

**Comment by mwalzer** [comment]
Yeah, I was trying to say 'the latest we use in other deployments and travis and so on'

**Comment by mwalzer** [comment]
Also works for most of my linux stuff. For alpine it is 
```
/ $ ls -lah /opt/thirdparty/XTandem/tandem.exe 
-rwxr-xr-x    1 root     root      756.0K May 29 21:13 /opt/thirdparty/XTandem/tandem.exe
/ $ /opt/thirdparty/XTandem/tandem.exe
/bin/sh: /opt/thirdparty/XTandem/tandem.exe: not found
```
anyone know about special needs of tandem.exe like shell or shared libs?

**Comment by jpfeuffer** [comment]
https://github.com/gliderlabs/docker-alpine/issues/219

**Comment by jpfeuffer** [comment]
My tip: Do not use alpine

**Comment by mwalzer** [comment]
Darn, yes :man_facepalming:  - I repressed all MUSL related memories from when I started building for alpine. Thanks for the link, didn't know about the compat lib!
Yeah though,  ~600Mb image for OpenMS+thirdparty sounds pretty neat to me, alas nasty stuff at some points. In any case: done. My tip: never stop trying something new.

**Comment by jpfeuffer** [comment]
Did you try reducing boost and QT to its minimum? Would be interesting, too, if we really need all that stuff in there.

**Comment by jpfeuffer** [comment]
Also superhirn might link in Xerces a second time, if you want some MB less.

**Comment by mwalzer** [comment]
cool! will try.
