### ISSUE TITLE
Update sage search engine

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/THIRDPARTY#101]
There was a new sage update.

Similar to my last update: https://github.com/OpenMS/THIRDPARTY/commit/0dda83f91697960235b4cb33a448c4f40c553e08

one needs to download the latest release from https://github.com/lazear/sage/releases/tag/v0.13.4

in particular, for these platforms:
https://github.com/lazear/sage/releases/download/v0.13.4/sage-v0.13.4-x86_64-apple-darwin.tar.gz
https://github.com/lazear/sage/releases/download/v0.13.4/sage-v0.13.4-x86_64-pc-windows-msvc.zip
https://github.com/lazear/sage/releases/download/v0.13.4/sage-v0.13.4-x86_64-unknown-linux-gnu.tar.gz

Extract the files and overwrite the files in the respective folders (e.g., for Linux the correct folder is in: https://github.com/OpenMS/THIRDPARTY/tree/master/Linux/64bit/Sage ).

**Comment by matteopilz** [comment]
Do we need some additional tests, to see if it works?

**Comment by jpfeuffer** [comment]
We could add a small CI test that just executes all TP executables :D
