### ISSUE TITLE
Update Sage to v0.14.1

### ISSUE THREAD

**Issue by lazear** [OpenMS/THIRDPARTY#104]
Using the same platforms as before: https://github.com/OpenMS/THIRDPARTY/issues/101

https://github.com/lazear/sage/releases/download/v0.14.1/sage-v0.14.1-x86_64-apple-darwin.tar.gz
https://github.com/lazear/sage/releases/download/v0.14.1/sage-v0.14.1-x86_64-pc-windows-msvc.zip
https://github.com/lazear/sage/releases/download/v0.14.1/sage-v0.14.1-x86_64-unknown-linux-gnu.tar.gz

I can also open a PR for this if needed.
On a side note, are you guys considering supporting aarch64 for linux or Mac? I realize not many other proteomics tools seem to support ARM architectures, but with Apple Silicon growing in popularity it might make sense?

**Comment by jpfeuffer** [comment]
ARM: Yes I think we are about to! CI is running already. Third-party tools are actually one of the remaining issues together with package naming.
I would be fine just having sage and the java tools as the only thirdparty tools for an initial ARM release.

**Comment by jpfeuffer** [comment]
Seems to be closed via https://github.com/OpenMS/THIRDPARTY/commit/e49256892b14c3abbe0e2e30788b143344e4da07

**Comment by jpfeuffer** [comment]
Thanks for releasing and letting us know!
