### ISSUE TITLE
Comet executable version differs in quay container and repo

### ISSUE THREAD

**Issue by jonasscheid** [OpenMS/THIRDPARTY#106]
Comet executable in recent container quay.io/biocontainers/openms-thirdparty:3.1.0--h9ee0642_3 differs from the one in this repo.

Container version: `TOPPBase.cpp(1588): Comet Version extracted is: '# comet_version 2023.01 rev. 0`

Version in this repo: `TOPPBase.cpp(1630): Comet Version extracted is: '# comet_version 2023.01 rev. 2 (7c9150d)`

Not sure how that could happen. @timosachsenberg Any ideas? They comet executable was exchanged a year ago --> [commit](https://github.com/OpenMS/THIRDPARTY/commit/e2152090f83531096ab771b608d561e56325d2c5)
before the 3.1.0 release.

The most recent comet version is needed to make sure the `pin` output and `pepxml` output of comet are the same. For more information see [release](https://github.com/UWPR/Comet/releases/tag/v2023.01.2)

Let me know if I can assist with anything

**Comment by timosachsenberg** [comment]
comet-ms bioconda is at 2023010-2 so this seems recent
hmm recipe links to: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/openms-meta/meta.yaml#L146
maybe one needs to specify 2023010-2 there and rebuild the package?
or just do a rebuild?
@jpfeuffer do you know

**Comment by jpfeuffer** [comment]
Yes, update and rebuild is the safest.

**Comment by jonasscheid** [comment]
Looks like the most recent release of comet is not on bioconda.. https://github.com/bioconda/bioconda-recipes/blob/c47bb585be9496842599e2e512a35dd120239528/recipes/comet-ms/meta.yaml#L10

So first we need to update that one and then rebuild. I can update comet and see if a simple version bump helps.

**Comment by jonasscheid** [comment]
https://github.com/bioconda/bioconda-recipes/pull/46567

**Comment by jonasscheid** [comment]
Someone familiar with this error? https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=53835&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=4dddc55b-10bc-50fc-ac68-7ff899b7a030
