### ISSUE TITLE
Sirius LIbraries

### ISSUE THREAD

**Issue by lukaszimmermann** [OpenMS/THIRDPARTY#19]
The `sirius` executable script required the libraries located in `THIRDPARTY/All/Sirius/lib` 
These are currently not included in the `CLASSPATH` for Sirius, so the sirius script will not work. I have to check how the libraries in the All directory can be included in the `sirius` script.
I think it would be best to just merge the contents of the `THIRDPARTY/All/Sirius/lib`  and the platform-specific `lib` dir upon deployment, but I do not know if this is possible. (It might be the  case that the dir contents are already merged when installed, then I would not be aware of it)

**Comment by oliveralka** [comment]
Not sure about that. If we know how the flat folder structure looks like we could alter the scripts for Linux and OsX and see if it is running.
1) look if libs are in the same folder (flat) - not sure about the folder structure. 
2) if not look at specific path `THIRDPARTY/All/Sirius/lib`
If that works we can ask the Sirius-guys if they could add the changes to the OpenMS THIRPARTY Sirius build for Linux/OsX  & windows. 

From:
`CLASSPATH="$APP_HOME/../../../All/Sirius/lib/*:${GUROBI_HOME}/lib/gurobi.jar"`
To:
`CLASSPATH="$APP_HOME:$APP_HOME/../../../All/Sirius/lib/*:${GUROBI_HOME}/lib/gurobi.jar"`

**Comment by timosachsenberg** [comment]
is this now fixed?

**Comment by lukaszimmermann** [comment]
yes
