### ISSUE TITLE
Update binaries

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/THIRDPARTY#2]
We should update and check the performance of newer versions of our Thirdparty software.

I checked briefly and saw that there are some major updates possible:

For XTandem we are at Sledgehammer from 2013 (last release 12/2015, http://www.thegpm.org/tandem/)
For MSGFPlus we are using the beta from 2014 (it just had a recent release in June16, https://omics.pnl.gov/software/ms-gf)
For Myrimatch there are no updates to expect
For Fido there are no updates to expect
For OMSSA we have 2.1.8 but newest is 2.1.9 (release in 2010, seems discontinued, might not be worth the upgrade trouble)

**Comment by timosachsenberg** [comment]
IIRC omssa did not update the version number to 1.9 so we might already have the most recent one

**Comment by timosachsenberg** [comment]
MSGF+ updated to newest version 20160629

**Comment by timosachsenberg** [comment]
xtandem is updated to vengence
pwiz is updated to 3.0.9935 (8/8/2916)
