### ISSUE TITLE
Sirius update overwrote modified RPATH

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/THIRDPARTY#26]
@oliveralka 
Your Sirius update overwrote some changes I made for debian packaging but nicely solved the softlink problem and reduces size.

We (or maybe even the distributors) should add the ORIGIN keyword to the RPATH of the libglpk libraries on Linux again so that the dpkg-shlibdeps program finds the dependency in the same folder (slightly annoying, I know but easy workaround).

See: http://cdash.openms.de/viewBuildError.php?buildid=238184

**Comment by oliveralka** [comment]
I'm not sure what to change, could you give me a pointer?

**Comment by oliveralka** [comment]
Thank you!
