### ISSUE TITLE
Merge OpenMS/windows-installer/thirdparty to here

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/THIRDPARTY#3]
In the windows-installer subrepo, there are binaries stored to be included in the installer. They seem to have diverged from the THIRDPARTY subrepo.
Either update them or better (this issue) remove the binaries from there and make sure that the installer scripts checkout the THIRDPARTY subrepo with the maintained binaries.

**Comment by mwalzer** [comment]
Yeah, I agree that the latter looks like the better option

**Comment by timosachsenberg** [comment]
I updated the search engines and pwiz. I think it is time to remove them from the windows-installer repository but I won't do it before I am sure this doesn't break the nightly builds.

**Comment by jpfeuffer** [comment]
Windows installer repository is not used anymore. NSIS scripts are in the OpenMS repo under the cmake folders (integrated into cmake). VCRedist etc is here.
