### ISSUE TITLE
Java 9/10 issue 

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/THIRDPARTY#46]
There seems to be an issue with some Adapters and a newer Java-Version.
As far as I was able to test  MSGFPlus and Sirius affected.

```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: javax.xml.bind.DataBindingException: javax.xml.bind.JAXBException
with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
```

There is already a fix for MSGFPlus (will open a PR).
MSGF+ Release v2018.01.30
`Java 9 compatibility: add dependencies on com.sun.xml.bind:jaxb-impl and jaxb:activation to support use with Java 9 (with some warnings). Without this change, users must supply the Java VM argument "--add-modules=java.xml.bind,java.activation"`
see https://github.com/MSGFPlus/msgfplus/releases/tag/v2018.01.30

**Comment by jpfeuffer** [comment]
Great thanks!
