### ISSUE TITLE
Update comet.exe

### ISSUE THREAD

**Issue by jonasscheid** [OpenMS/THIRDPARTY#97]
Hi!
Would be cool to use the new comet.exe from the [latest release](https://github.com/UWPR/Comet/releases). The current one is 4 years old and contains bugs that were resolved during the years. For example I can run converted IM data with the new comet.exe, with the old I ran into issues. See https://github.com/OpenMS/OpenMS/issues/6274.

**Comment by jonasscheid** [comment]
@jpfeuffer

**Comment by jpfeuffer** [comment]
Makes sense. Feel free to upload new executables here.

**Comment by jonasscheid** [comment]
Fixed
